name: Build and Push WSO2EI Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GitLab Container Registry
        run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login gitlab.dokuma.digital -u "${{ secrets.GITLAB_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG="gitlab.dokuma.digital/${{ secrets.GITLAB_REPO }}:latest"
          echo "Building image: $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" .

      - name: Push image to GitLab
        run: |
          IMAGE_TAG="gitlab.dokuma.digital/${{ secrets.GITLAB_REPO }}:latest"
          docker push "$IMAGE_TAG"
