name: Build and Push WSO2EI Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitLab Registry
        run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login gitlab.dokuma.digital -u "${{ secrets.GITLAB_USER }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="gitlab.dokuma.digital/wso-sample/wso2-ei-demo:latest"
          echo "Building image: $IMAGE_TAG"
          docker buildx build --platform linux/amd64 -t "$IMAGE_TAG" . --push
