name: Build and Push WSO2EI Docker Image to Dokuma GitLab Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitLab Dokuma Registry
        run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login gitlab.dokuma.digital -u "${{ secrets.GITLAB_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE="gitlab.dokuma.digital/${{ secrets.GITLAB_REPO }}:latest"
          docker build -t $IMAGE .
          echo "Built image: $IMAGE"

      - name: Push Docker image
        run: |
          IMAGE="gitlab.dokuma.digital/${{ secrets.GITLAB_REPO }}:latest"
          docker push $IMAGE
